
#program: run_training.py
method: bayes
name: sweep

metric:
    name: val_loss
    goal: minimize

early_terminate:
    type: "hyperband"
    min_iter: 5

parameters:
    #n_epochs:
    #    values: 1 #10
    batch_size:
        values: [4, 5, 6]
    learnin_rate:
        distribution: uniform
        min: 0.000001
        max: 0.005
    optimizer:
        values: ["Adam", "AdamW", "SGD"]
    weight_decay:
        #values: [null, 0.0001, 0.001, 0.004, 0.01]
        distribution: uniform
        min: 0.0
        max: 0.02
        
    lr_decay:
        #values: [0.05, 0.01, 0.1, 0.2, 0.5, 0.8]
        distribution: uniform
        min: 0.0
        max: 0.5
        
    lr_scheduler:
        values: [null, "cosine", "polynomial", "exponential", "time", "plateau_reduce",
                 "tf_cosine", "tf_exp", "tf_invtime"]
    warmup_epoch:
        values: [0, 1, 2, 3, 4, 5]
        
    




