## Training config file

ds_path: "resources/Task01_BrainTumour/"
batch_size: 3
crop_size: [128, 128]
train_test_split: 0.80
val_test_split: 0.50
n_classes: 4
seed: 42

n_epochs: 20
learning_rate: 0.00001


wandb: False
