method: "bayes"
name: "sweeps-3"
metric:
    name: "val_soft_dice_loss" #"val_loss.min"
    goal: "minimize"

parameters:
    n_epochs:
        value: 12 #10
    #batch_size:
    #    value: 5
    learning_rate:
        distribution: "uniform"
        min: 0.001
        max: 0.005
    #optimizer:
    #    #values: ["Adam", "AdamW", "SGD"]

    weight_decay:
        #values: [null, 0.0001, 0.001, 0.004, 0.01]
        distribution: "uniform"
        min: 0.001
        max: 0.01
        
    lr_decay:
        #values: [0.05, 0.01, 0.1, 0.2, 0.5, 0.8]
        distribution: "uniform"
        min: 0.0
        max: 0.5
        
    lr_scheduler:
        values: ["cosine", "polynomial", "exponential", "time", "plateau_reduce",
                 "tf_cosine", "tf_exp"]
    #warmup_epoch:
    #    values: [0, 1, 2, 3, 4, 5]
        

#early_terminate:
#    type: "hyperband"
#    min_iter: 5




#weight decay -> min 0.0075 , max: 0.02
# 